export const GET_KANBANLIST = "GET_KANBANLIST";
export const ADD_CARD = "ADD_CARD";
export const GET_PROJECTLIST = "GET_PROJECTLIST";
export const CHANGE_PROJECTID = "CHANGE_PROJECTID";
export const ADD_NEWPROJECT = "ADD_NEWPROJECT";
export const CANCEL_NEWPROJECT = "CANCEL_NEWPROJECT";
export const ADD_LIST = "ADD_LIST";